Repository besp-team1/NetMong, pull requests merged in 2023-11, with the labels that each got.

#28 Fix: 로그인 이슈 해결
  src/main/java/com/ll/netmong/base/exceptionhandler/GlobalExceptionHandler.java
  src/main/java/com/ll/netmong/domain/member/dto/JoinRequest.java
  src/test/java/com/ll/netmong/member/service/MemberServiceTest.java
Labels: 🐞 bug

#29 Feature/#23
  src/main/java/com/ll/netmong/domain/park/controller/ParkController.java
  src/main/java/com/ll/netmong/domain/park/dto/request/ParkRequest.java
  src/main/java/com/ll/netmong/domain/park/dto/response/ParkResponse.java
  src/main/java/com/ll/netmong/domain/park/entity/Park.java
  src/main/java/com/ll/netmong/domain/park/repository/ParkRepository.java
  src/main/java/com/ll/netmong/domain/park/service/ParkService.java
  src/main/java/com/ll/netmong/domain/park/service/ParkServiceImpl.java
  src/test/java/com/ll/netmong/domain/park/service/ParkServiceImplTest.java
Labels: 🦊 refactor

#31 Feature/#22 댓글 작성자 연결
  src/main/java/com/ll/netmong/common/DataNotFoundException.java
  src/main/java/com/ll/netmong/domain/postComment/controller/PostCommentController.java
  src/main/java/com/ll/netmong/domain/postComment/dto/response/PostCommentResponse.java
  src/main/java/com/ll/netmong/domain/postComment/entity/PostComment.java
  src/main/java/com/ll/netmong/domain/postComment/repository/PostCommentRepository.java
  src/main/java/com/ll/netmong/domain/postComment/service/PostCommentService.java
  src/main/java/com/ll/netmong/domain/postComment/service/PostCommentServiceImpl.java
  src/test/java/com/ll/netmong/domain/comment/service/PostCommentServiceImplTest.java
Labels: ✨ enhancement, 🦊 refactor

#33 Feature/#21 포스트 등록, 조회, 삭제, 수정, 전체 포스트 조회
  src/main/java/com/ll/netmong/common/PermissionDeniedException.java
  src/main/java/com/ll/netmong/domain/post/controller/PostController.java
  src/main/java/com/ll/netmong/domain/post/dto/response/PostResponse.java
  src/main/java/com/ll/netmong/domain/post/entity/Post.java
  src/main/java/com/ll/netmong/domain/post/service/PostService.java
  src/main/java/com/ll/netmong/domain/post/service/PostServiceImpl.java
Labels: ✨ enhancement

#35 Feature/#34 포스트 상세에서 postId 값이 출력될 수 있도록 수정
  src/main/java/com/ll/netmong/domain/post/dto/response/PostResponse.java
Labels: 🐥 fix

#38 Fix: 포스트 업로드시 PostResponse가 반환되도록 수정
  src/main/java/com/ll/netmong/domain/post/controller/PostController.java
  src/main/java/com/ll/netmong/domain/post/service/PostService.java
  src/main/java/com/ll/netmong/domain/post/service/PostServiceImpl.java
Labels: 🐥 fix

#42 Feature/#39 createDate 수정 및 WebConfig 추가
  src/main/java/com/ll/netmong/base/config/WebConfig.java
  src/main/java/com/ll/netmong/base/config/WebSecurityConfig.java
  src/main/java/com/ll/netmong/domain/post/controller/PostController.java
  src/main/java/com/ll/netmong/domain/post/dto/response/PostResponse.java
  src/main/resources/application.yml
Labels: ✨ enhancement, 🐥 fix

#48 Feature/#43 댓글 페이징 처리
  src/main/java/com/ll/netmong/common/PageResponse.java
  src/main/java/com/ll/netmong/domain/postComment/controller/PostCommentController.java
  src/main/java/com/ll/netmong/domain/postComment/repository/PostCommentRepository.java
  src/main/java/com/ll/netmong/domain/postComment/service/PostCommentService.java
  src/main/java/com/ll/netmong/domain/postComment/service/PostCommentServiceImpl.java
Labels: ✨ enhancement

#49 Feat/#47 상품 조회 페이징 처리 기능 추가
  src/main/java/com/ll/netmong/domain/product/controller/ProductController.java
  src/main/java/com/ll/netmong/domain/product/dto/response/ViewAllResponse.java
  src/main/java/com/ll/netmong/domain/product/service/ProductService.java
  src/main/java/com/ll/netmong/domain/product/service/ProductServiceImpl.java
Labels: ✨ enhancement

#52 Feat/#51 포스트 페이징 처리
  src/main/java/com/ll/netmong/domain/post/controller/PostController.java
  src/main/java/com/ll/netmong/domain/post/dto/response/PostResponse.java
  src/main/java/com/ll/netmong/domain/post/service/PostService.java
  src/main/java/com/ll/netmong/domain/post/service/PostServiceImpl.java
Labels: ✨ enhancement
