Repository besp-team1/NetMong, pull requests merged in 2023-12, with the labels that each got.

#61 Feature/#32 포스트 좋아요 기능
  src/main/java/com/ll/netmong/base/exceptionhandler/GlobalExceptionHandler.java
  src/main/java/com/ll/netmong/domain/likedPost/controller/LikedPostController.java
  src/main/java/com/ll/netmong/domain/likedPost/dto/request/LikedPostRequest.java
  src/main/java/com/ll/netmong/domain/likedPost/dto/response/LikedPostResponse.java
  src/main/java/com/ll/netmong/domain/likedPost/entity/LikedPost.java
  src/main/java/com/ll/netmong/domain/likedPost/exception/DuplicateLikeException.java
  src/main/java/com/ll/netmong/domain/likedPost/repository/LikedPostRepository.java
  src/main/java/com/ll/netmong/domain/likedPost/service/LikedPostService.java
  src/main/java/com/ll/netmong/domain/likedPost/service/LikedPostServiceImpl.java
  src/main/java/com/ll/netmong/domain/member/entity/Member.java
  src/main/java/com/ll/netmong/domain/post/entity/Post.java
  src/test/java/com/ll/netmong/domain/comment/service/PostCommentServiceImplTest.java
  src/test/java/com/ll/netmong/domain/likedPost/service/LikedPostServiceImplTest.java
Labels: ✨ enhancement, 🦊 refactor

#71 Feature/#69 포스트 신고 기능
  src/main/java/com/ll/netmong/base/exceptionhandler/GlobalExceptionHandler.java
  src/main/java/com/ll/netmong/domain/reportPost/controller/ReportPostController.java
  src/main/java/com/ll/netmong/domain/reportPost/dto/request/ReportPostRequest.java
  src/main/java/com/ll/netmong/domain/reportPost/dto/response/ReportPostResponse.java
  src/main/java/com/ll/netmong/domain/reportPost/entity/ReportPost.java
  src/main/java/com/ll/netmong/domain/reportPost/exception/DuplicateReportException.java
  src/main/java/com/ll/netmong/domain/reportPost/exception/InvalidReportException.java
  src/main/java/com/ll/netmong/domain/reportPost/repository/ReportPostRepository.java
  src/main/java/com/ll/netmong/domain/reportPost/service/ReportPostService.java
  src/main/java/com/ll/netmong/domain/reportPost/service/ReportPostServiceImpl.java
  src/main/java/com/ll/netmong/domain/reportPost/util/ReportType.java
  src/test/java/com/ll/netmong/domain/reportPost/service/ReportPostServiceImplTest.java
Labels: ✨ enhancement

#73 Feature/#66 공원 좋아요 기능 구현
  src/main/java/com/ll/netmong/domain/likePark/controller/LikedParkController.java
  src/main/java/com/ll/netmong/domain/likePark/dto/request/LikedParkRequest.java
  src/main/java/com/ll/netmong/domain/likePark/dto/response/LikedParkResponse.java
  src/main/java/com/ll/netmong/domain/likePark/entity/LikedPark.java
  src/main/java/com/ll/netmong/domain/likePark/repository/LikedParkRepository.java
  src/main/java/com/ll/netmong/domain/likePark/service/LikedParkService.java
  src/main/java/com/ll/netmong/domain/likePark/service/LikedParkServiceImpl.java
  src/main/java/com/ll/netmong/domain/park/controller/ParkController.java
  src/main/java/com/ll/netmong/domain/park/dto/response/ParkResponse.java
  src/main/java/com/ll/netmong/domain/park/entity/Park.java
  src/main/java/com/ll/netmong/domain/park/service/ParkService.java
  src/main/java/com/ll/netmong/domain/park/service/ParkServiceImpl.java
  src/main/java/com/ll/netmong/domain/parkComment/entity/ParkComment.java
  src/main/java/com/ll/netmong/domain/parkComment/repository/ParkCommentRepository.java
  src/main/java/com/ll/netmong/domain/parkComment/service/ParkCommentServiceImpl.java
  src/test/java/com/ll/netmong/domain/likePark/service/LikedParkServiceImplTest.java
  src/test/java/com/ll/netmong/domain/park/service/ParkServiceImplTest.java
  src/test/java/com/ll/netmong/domain/parkComment/service/ParkCommentServiceImplTest.java
Labels: ✨ enhancement

#76 Feature/#65 포스트 검색 기능, 검색 페이지 페이징 기능
  src/main/java/com/ll/netmong/domain/post/controller/PostController.java
  src/main/java/com/ll/netmong/domain/post/dto/request/PostRequest.java
  src/main/java/com/ll/netmong/domain/post/entity/Post.java
  src/main/java/com/ll/netmong/domain/post/repository/PostRepository.java
  src/main/java/com/ll/netmong/domain/post/service/PostService.java
  src/main/java/com/ll/netmong/domain/post/service/PostServiceImpl.java
Labels: ✨ enhancement

#80 Feature/#74 댓글 신고, 신고된 댓글 조회
  src/main/java/com/ll/netmong/base/config/WebSecurityConfig.java
  src/main/java/com/ll/netmong/base/exceptionhandler/GlobalExceptionHandler.java
  src/main/java/com/ll/netmong/common/InitData.java
  src/main/java/com/ll/netmong/domain/member/entity/Member.java
  src/main/java/com/ll/netmong/domain/member/repository/MemberJpaRepository.java
  src/main/java/com/ll/netmong/domain/member/repository/MemberRepository.java
  src/main/java/com/ll/netmong/domain/member/repository/MemberRepositoryImpl.java
  src/main/java/com/ll/netmong/domain/post/service/PostService.java
  src/main/java/com/ll/netmong/domain/post/service/PostServiceImpl.java
  src/main/java/com/ll/netmong/domain/postComment/controller/PostCommentController.java
  src/main/java/com/ll/netmong/domain/postComment/entity/PostComment.java
  src/main/java/com/ll/netmong/domain/postComment/service/PostCommentService.java
  src/main/java/com/ll/netmong/domain/postComment/service/PostCommentServiceImpl.java
  src/main/java/com/ll/netmong/domain/reportPost/controller/ReportPostController.java
  src/main/java/com/ll/netmong/domain/reportPost/dto/request/ReportPostRequest.java
  src/main/java/com/ll/netmong/domain/reportPost/dto/response/ReportPostResponse.java
  src/main/java/com/ll/netmong/domain/reportPost/entity/ReportPost.java
  src/main/java/com/ll/netmong/domain/reportPost/service/ReportPostService.java
  src/main/java/com/ll/netmong/domain/reportPost/service/ReportPostServiceImpl.java
  src/main/java/com/ll/netmong/domain/reports/controller/ReportAdminController.java
  src/main/java/com/ll/netmong/domain/reports/controller/ReportController.java
  src/main/java/com/ll/netmong/domain/reports/dto/request/ReportRequest.java
  src/main/java/com/ll/netmong/domain/reports/dto/response/ReportCommentResponse.java
  src/main/java/com/ll/netmong/domain/reports/dto/response/ReportPostResponse.java
  src/main/java/com/ll/netmong/domain/reports/entity/Report.java
  src/main/java/com/ll/netmong/domain/reports/entity/ReportComment.java
  src/main/java/com/ll/netmong/domain/reports/entity/ReportPost.java
  src/main/java/com/ll/netmong/domain/reports/exception/DuplicateReportException.java
  src/main/java/com/ll/netmong/domain/reports/exception/InvalidReportException.java
  src/main/java/com/ll/netmong/domain/reports/repository/ReportCommentRepository.java
  src/main/java/com/ll/netmong/domain/reports/repository/ReportPostRepository.java
  src/main/java/com/ll/netmong/domain/reports/service/ReportService.java
  src/main/java/com/ll/netmong/domain/reports/service/ReportServiceImpl.java
  src/main/java/com/ll/netmong/domain/reports/util/ReportType.java
  src/main/resources/application.yml
  src/test/java/com/ll/netmong/domain/reportPost/service/ReportPostServiceImplTest.java
  src/test/java/com/ll/netmong/domain/reports/service/ReportServiceImplTest.java
  src/test/java/com/ll/netmong/member/mock/FakeMemberRepository.java
Labels: ✨ enhancement, 🦊 refactor

#79 Feature/#75 상품이름 검색, 카테고리 검색 기능, 상품 재고에 다한 비관적 락 기능
  build.gradle
  src/main/java/com/ll/netmong/base/config/TransactionConfig.java
  src/main/java/com/ll/netmong/domain/cart/entity/Cart.java
  src/main/java/com/ll/netmong/domain/cart/itemCart/entity/ItemCart.java
  src/main/java/com/ll/netmong/domain/cart/itemCart/service/ItemCartService.java
  src/main/java/com/ll/netmong/domain/cart/itemCart/service/ItemCartServiceImpl.java
  src/main/java/com/ll/netmong/domain/cart/service/CartServiceImpl.java
  src/main/java/com/ll/netmong/domain/image/entity/Image.java
  src/main/java/com/ll/netmong/domain/product/controller/ProductController.java
  src/main/java/com/ll/netmong/domain/product/dto/response/ViewAllResponse.java
  src/main/java/com/ll/netmong/domain/product/entity/Product.java
  src/main/java/com/ll/netmong/domain/product/repository/ProductRepository.java
  src/main/java/com/ll/netmong/domain/product/service/ProductService.java
  src/main/java/com/ll/netmong/domain/product/service/ProductServiceImpl.java
  src/main/java/com/ll/netmong/domain/product/util/ProductErrorCode.java
  src/main/resources/application.yml
  src/test/java/com/ll/netmong/domain/cart/itemCart/service/ItemCartServiceImplTest.java
Labels: ✨ enhancement

#81 Feature/#77 공원 댓글 테스트 리팩토링 및 공원 좋아요 낙관적 락 적용
  .gitignore
  src/main/java/com/ll/netmong/base/exceptionhandler/GlobalExceptionHandler.java
  src/main/java/com/ll/netmong/domain/likePark/controller/LikedParkController.java
  src/main/java/com/ll/netmong/domain/likePark/service/LikedParkServiceImpl.java
  src/main/java/com/ll/netmong/domain/park/entity/Park.java
  src/main/java/com/ll/netmong/domain/park/repository/ParkRepository.java
  src/test/java/com/ll/netmong/domain/likePark/service/LikedParkServiceImplTest.java
  src/test/java/com/ll/netmong/domain/parkComment/service/ParkCommentServiceImplTest.java
Labels: ✨ enhancement, 🦊 refactor

#84 Feature/#78
  src/main/java/com/ll/netmong/domain/hashtag/entity/Hashtag.java
  src/main/java/com/ll/netmong/domain/hashtag/repository/HashtagRepository.java
  src/main/java/com/ll/netmong/domain/hashtag/service/HashtagService.java
  src/main/java/com/ll/netmong/domain/hashtag/service/HashtagServiceImpl.java
  src/main/java/com/ll/netmong/domain/likedPost/entity/LikedPost.java
  src/main/java/com/ll/netmong/domain/post/controller/PostController.java
  src/main/java/com/ll/netmong/domain/post/entity/Post.java
  src/main/java/com/ll/netmong/domain/post/repository/PostRepository.java
  src/main/java/com/ll/netmong/domain/post/service/PostService.java
  src/main/java/com/ll/netmong/domain/post/service/PostServiceImpl.java
  src/main/java/com/ll/netmong/domain/postHashtag/entity/PostHashtag.java
  src/main/java/com/ll/netmong/domain/postHashtag/repository/PostHashtagRepository.java
  src/main/java/com/ll/netmong/domain/postHashtag/service/PostHashtagService.java
  src/main/java/com/ll/netmong/domain/postHashtag/service/PostHashtagServiceImpl.java
Labels: ✨ enhancement

#88 Refactor: 장바구니 조회시 상품 id도 반환해주도록
  src/main/java/com/ll/netmong/domain/cart/dto/response/ViewCartResponse.java
  src/main/java/com/ll/netmong/domain/cart/itemCart/service/ItemCartServiceImpl.java
Labels: 🦊 refactor

#92 Refactor: ParkCommentServiceImplTest 테스트 리팩토링
  src/test/java/com/ll/netmong/domain/parkComment/service/ParkCommentServiceImplTest.java
Labels: 🦊 refactor

#101 Fix/#100 대댓글 postId 저장 안 되는 문제 해결
  src/main/java/com/ll/netmong/domain/postComment/service/PostCommentServiceImpl.java
Labels: 🐥 fix

#105 Fix/#104 댓글 작성자 변경
  src/main/java/com/ll/netmong/domain/postComment/service/PostCommentServiceImpl.java
Labels: 🐥 fix

#114 Refactor: 포스트 테스트코드 수정
  src/test/java/com/ll/netmong/domain/post/service/PostServiceImplTest.java
Labels: 🦊 refactor

#122 Refactor: 수정일 기준 포스트 내림차순 조회
  src/main/java/com/ll/netmong/domain/post/controller/PostController.java
Labels: 🦊 refactor

#133 Feature/#132 공원 댓글 수정, 삭제 findByEmail로 username을 찾을 수 있도록 수정
  src/main/java/com/ll/netmong/domain/parkComment/service/ParkCommentServiceImpl.java
  src/test/java/com/ll/netmong/domain/parkComment/service/ParkCommentServiceImplTest.java
Labels: 🐥 fix
